version: "3.9"

services:
  # PHP Service Laravel Application
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-blog
      - laravel-nuxt-network
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.1.0
    container_name: db_blog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel-blog
      - laravel-nuxt-network

  # Nginx Service
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-blog
      - laravel-nuxt-network

networks:
  laravel-blog:
    driver: bridge
  laravel-nuxt-network:
    external: true
